name: Module CI/CD

on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    # Install dependancies from NPM
    - name: Install dependancies
      shell: bash
      id: install-dependancies
      run: npm i

    # Get the name from 'module.json'
    - name: Build
      shell: bash
      id: build
      run: npm run build

    # Useful only for the template so we can leave the manifest and download urls empty
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_latest
      uses: microsoft/variable-substitution@v1
      with:
        files: './dist/module.json'
      env:
        version: ${{ RELEASE_VERSION }}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/latest/download/module.zip

    # create a zip file with all files required by the module to add to the release
    - name: Package
      shell: bash
      id: package
      run: npm run package

    # Update the 'latest' release
    - name: Update Latest Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Latest
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json, ./package/module.zip'
        tag: latest

    #Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: './dist/module.json'
      env:
        version: ${{ RELEASE_VERSION }}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/download/${{RELEASE_VERSION}}/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{RELEASE_VERSION}}/module.zip
    
    # Create a release for this specific version
    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ RELEASE_VERSION }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json, ./package/module.zip'
        tag: ${{ RELEASE_VERSION }}
